import { Inter } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Short Film App",
  description: "Generated by Alessandrovaru",
};

// config your font
const microgramma = localFont({
  src: "../../public/fonts/micro.otf",
  variable: "--microgramma-font",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${microgramma.variable}`}>{children}</body>
    </html>
  );
}
